global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m
  receiver: 'alert-bot'

receivers:
  - name: 'alert-bot'
    webhook_configs:
      - url: 'http://alert_bot:5000/webhook'
        send_resolved: true