global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask_api'
    static_configs:
      - targets: ['flask_api:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

rule_files:
  - /etc/prometheus/alert_rules.yml